name: Test find_lowest_number.py
on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: test with 10 numbers
        run: python3 find_lowest_number.py < .github/test_data/test1_input.txt > test_data/test1_output.txt && diff test_data/test1_output.txt .github/test_data/test1_expected.txt

      

       
     

