name: Test find_lowest_number.py
on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: test with 10 numbers
        run: python find_lowest_number.py > .github/test_data/test1_input.txt .github/test_data/test1_output.txt && diff .github/test_data/test1_output.txt .gtihub/test_data/test1_expected.txt

      - name: test with 1 number
        run: python find_lowest_number.py > .github/test_data/test2_input.txt .github/test_data/test2_output.txt && diff .github/test_data/test2_output.txt .gtihub/test_data/test3_expected.txt

      - name: test with no number file
        run: python find_lowest_number.py > .github/test_data/test3_input.txt .github/test_data/test3_output.txt && diff .github/test_data/test3_output.txt .gtihub/test_data/test3_expected.txt

     


