name: Test find_lowest_number.py
on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: produce test1_output.txt
        run: python find_lowest_number.py > test1_input.txt

      - name: Compare expected output to actual
        run: diff test1_expected.txt test1_input.txt

      

       
     

