name: Automated Testing
on:
  push:
    branches:
      - main
jobs:
  automated_testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Produce Test 1 Output
        run: python3 find_lowest_number.py > test_data/test1_input.txt

      - name: Test 1
        run: diff -u test_data/test1_expected.txt test_data/test1_input.txt

       
     

